GET http://localhost:3000/partner/voucher

###

POST http://localhost:3000/partner/promotion
Content-Type: application/json

{
    "title" : "A", 
    "description" : "A", 
    "start" : "2023-05-13",
    "end" : "2023-05-15",
    "partnerID" : null,
    "vouchers" : [
        {
            "id" : 1,
            "quantity" : 30
        },
        {
            "id" : 2,
            "quantity" : 50
        }
    ]
}

###

POST http://localhost:3000/user/signin
Content-Type: application/json
{
    "email" : "customer@gmail.com", 
    "password" : "123", 
    "role" : "customer",
}
