GET http://localhost:3000/partner/promotion?id=1


###

POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email" : "partner@gmail.com", 
    "password" : "123", 
    "role" : "partner"
}

###

POST http://localhost:3000/user/signin
Content-Type: application/json
{
    "email" : "customer@gmail.com", 
    "password" : "123", 
    "role" : "customer",
}
