GET http://localhost:3000/partner/voucher
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsImlhdCI6MTY4NDY1NzUzN30.N1WXXY5blKOh6Oyuhk8LXOqvGq6eOFhT09HCsqiiff0

###

PUT http://localhost:3000/partner/edit
Content-Type: application/json

{
    "id" : 1,
    "password" : "321",
    "address" : "Test",
    "name" : "Test"
}

###

POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email" : "partner@gmail.com", 
    "password" : "123", 
    "role" : "partner",
}

###
GET http://localhost:3000/customer/promotion
